### ISSUE TITLE
RuntimeError: Error in request

### ISSUE THREAD

**Issue by dogweather** [socrata/soda-ruby#15]
Is it possible that `soda-ruby` isn't ruby 2.2.0-compatible?

```ruby
RuntimeError: Error in request: 
from /Users/xxx/.rvm/gems/ruby-2.2.0/gems/soda-ruby-0.2.13/lib/soda/client.rb:163:in `handle_response'

```

I get this error running the [example](https://github.com/socrata/soda-ruby) but with my app's app token.

**Comment by dogweather** [comment]
Actually, maybe it's how I'm using the library. What exactly, should the value of `domain` be? Something related to my app?

**Comment by chrismetcalf** [comment]
@dogweather What dataset are you trying to access? That'll determine what the `domain` is that you want to provide.

**Comment by dogweather** [comment]
Thanks. It's: https://data.cityofnewyork.us/Health/DOHMH-New-York-City-Restaurant-Inspection-Results/xx67-kt59

**Comment by chrismetcalf** [comment]
Yep, so you'd want to initialize your client like this:

    client = SODA::Client.new({:domain => "data.cityofnewyork.us", :app_token => "YOURAPPTOKENGOESHERE"})

**Comment by dogweather** [comment]
Ah hah, thanks. I was looking in the About/Meta and Export tabs for a `domain` attribute. :-)
