### ISSUE TITLE
SODA::Client#post_form calls misspelled method

### ISSUE THREAD

**Issue by cyranix** [socrata/soda-ruby#22]
https://github.com/socrata/soda-ruby/blob/master/lib/soda/client.rb#L119 — this calls `resoure_path` instead of `resource_path`.

**Comment by kerrizor** [comment]
This appears fixed in #23 and should be closed.

**Comment by clint-tseng** [comment]
Indeed — thanks, @kerrizor!

**Comment by chrismetcalf** [comment]
:+1:
