### ISSUE TITLE
wiki documentation?

### ISSUE THREAD

**Issue by michaelachrisco** [socrata/soda-ruby#32]
I have a sample app that we created at a small local competition. I can add the rake task into the docs. 

I was wondering what the preference is: Wiki documentation, README, or git-pages?

**Comment by chrismetcalf** [comment]
@michaelachrisco Is it a full project or just a `Rakefile`? If it's just a single file, a Gist + a wiki entry might be appropriate.

**Comment by michaelachrisco** [comment]
Ok made the gist real quick. When I get a chance ill add in the wiki description: https://gist.github.com/michaelachrisco/dff796c04701c96c1154

**Comment by michaelachrisco** [comment]
Closed as gist takes care of description. 

(opinion) README.md and official docs are better for the gem.
