### ISSUE TITLE
400 bad request

### ISSUE THREAD

**Issue by syllogismus** [socrata/soda-ruby#35]
hi,
adding filters and such ends up in a bad request:

#NYC JOBS
#https://data.cityofnewyork.us/resource/rvhx-8trz.json
domain = "data.cityofnewyork.us"

client = SODA::Client.new({:domain => domain, :app_token => token })
# response = client.get("rvhx-8trz", {"$where" => "posting_date > '2015/01/01'"})
>> bad
       

#response = client.get("rvhx-8trz",{'where' => "'job_id = '320756008'"})
>> bad

#response = client.get("rvhx-8trz",{"$limit" => 100 , "$where" => "posting_date > '2015/01/1' AND posting_date < '2016/1/1'" , "$order" => "posting_date DESC"})
>> bad

any ideas?

thx

**Comment by syllogismus** [comment]
ok that was my bad.

please look at this: the website reports 12 results, i get 0


domain = "data.illinois.gov"
client = SODA::Client.new({:domain => domain, :app_token => token })
response = client.get("traj-88ek", {'$where' => "'bid_date' = '8/18/11'"})
>> count > 0 (website: 12)

thx

**Comment by marks** [comment]
@syllogismus -- I am not seeing a `bid_date` column in that dataset. I think the query is being interpreted by Socrata as "if the string bid_date equals 8/18/11" which would never be true. When you use `bid_date`  instead of `'bid_date'` you will get an error that

**Comment by syllogismus** [comment]
ok, all good - that works!
thank you
