### ISSUE TITLE
Support for Rails 5?

### ISSUE THREAD

**Issue by jspanjers** [socrata/soda-ruby#42]
Since commit https://github.com/socrata/soda-ruby/commit/2d22a03a8051da945ec2dda8c3bb3bd628c1f0b8
sody-ruby has a dependency on rails 4.

Line:
s.add_dependency 'activesupport', '~> 4.2.5'

Is it intentional that you cannot install  soda-ruby in combination with rails 5?

**Comment by chrismetcalf** [comment]
Not intentional at all, @jspanjers! Let me see if I can remove that dependency or at least the version restriction.

**Comment by chrismetcalf** [comment]
@jspanjers Looks like I removed the need for that gem entirely, so I just removed it from the `gemspec`. `0.2.23` removes the dependency, and is published to rubygems.org! 🍺
